# Generated by Django 4.1.3 on 2022-11-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_review', '0006_profile_hasconsent_profile_survey_one_iscomplete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hasLottery',
            field=models.BooleanField(default=False),
        ),
    ]
